
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: net-tools
  name: net-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-tools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: net-tools
    spec:
      containers:
      - image: tehilathestudent/net-tools
        command: 
          - "sleep"
        args: 
         - "infinity"
        name: net-tools
        env:
          - name: http_proxy
            value: http://7.182.101.79:3128
          - name: https_proxy
            value: http://7.182.101.79:3128
          - name: HTTP_PROXY
            value: http://7.182.101.79:3128
          - name: HTTPS_PROXY
            value: http://7.182.101.79:3128
          - name: no_proxy
            value: localhost,127.0.0.1,go-server-svc,go-client-svc
        resources: {}
status: {}
