apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: codearts
spec:
  project: default
  source:
    repoURL: https://github.com/TehilaTheStudent/argocd-apps.git
    path: argocd-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: codearts
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true

