apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: calico-quickstart
spec:
  type: ClusterIP  # default type when --type is not specified
  selector:
    app: nginx  # assumes your Deployment has label `app: nginx`
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
