apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codeart
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: codearts/crds
    repoURL: https://codehub.devcloud.ap-southeast-3.huaweicloud.com/b3f25c9ab5cb457b97aa19bbc06b2743/crossplane-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
