apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 80
  name: services-go-server-calico
  namespace: codearts
spec:
  destination:
    namespace: services-go-server-calico
    server: https://7.182.101.79:30022
  project: learn-services
  source:
    path: services/go-server
    repoURL: https://github.com/TehilaTheStudent/k8s-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
